<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTIwcIx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTIwcIx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTIwcIx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTIwcIx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNTIwcIx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NTIwcIx',
    'container.build_id' => '9f30380a',
    'container.build_time' => 1646550460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTIwcIx');
